apiVersion: v1
kind: Namespace
metadata:
  name: @namespace@
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: @label@
  name: @label@
  namespace: @namespace@
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: @label@
  template:
    metadata:
      namespace: @namespace@
      labels:
        app: @label@
    spec:
      containers:
      - image: cr-p-001-registry-vpc.cn-hangzhou.cr.aliyuncs.com/@repos@/@image@
        imagePullPolicy: Always
        name: @label@
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
      dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  name: @label@-external-80
  namespace: @namespace@
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
spec:
  ports:
    - name: http
      port: 443
      protocol: TCP
      targetPort: 80
  selector:
    app: @label@
  type: LoadBalancer
